### ISSUE TITLE
Update Events API readme

### ISSUE THREAD

**Issue by tulios** [klarna/phobos_db_checkpoint#15]
Add the new endpoints to the section __Events API__ in the readme.

https://github.com/klarna/phobos_db_checkpoint/blob/master/lib/phobos_db_checkpoint/events_api.rb#L83

https://github.com/klarna/phobos_db_checkpoint/blob/master/lib/phobos_db_checkpoint/events_api.rb#L102

**Comment by klippx** [comment]
#16
